# Generated by Django 5.2.8 on 2026-01-27 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPageFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'A4 Portrait', 'Letter Landscape'", max_length=50, unique=True, verbose_name='Name')),
                ('width', models.DecimalField(decimal_places=2, help_text='Page width in millimeters', max_digits=6, verbose_name='Width (mm)')),
                ('height', models.DecimalField(decimal_places=2, help_text='Page height in millimeters', max_digits=6, verbose_name='Height (mm)')),
                ('orientation', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', max_length=10, verbose_name='Orientation')),
                ('margin_top', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='Top Margin (mm)')),
                ('margin_bottom', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='Bottom Margin (mm)')),
                ('margin_left', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='Left Margin (mm)')),
                ('margin_right', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='Right Margin (mm)')),
                ('is_default', models.BooleanField(default=False, help_text='Only one format can be default', verbose_name='Is Default')),
            ],
            options={
                'verbose_name': 'Report Page Format',
                'verbose_name_plural': 'Report Page Formats',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('primary_color', models.CharField(default='#333333', help_text='Hex color code (e.g., #333333)', max_length=7, verbose_name='Primary Color')),
                ('secondary_color', models.CharField(default='#666666', max_length=7, verbose_name='Secondary Color')),
                ('accent_color', models.CharField(default='#0066cc', max_length=7, verbose_name='Accent Color')),
                ('background_color', models.CharField(default='#ffffff', max_length=7, verbose_name='Background Color')),
                ('text_color', models.CharField(default='#000000', max_length=7, verbose_name='Text Color')),
                ('font_family', models.CharField(default='Arial, sans-serif', max_length=200, verbose_name='Font Family')),
                ('font_size', models.CharField(default='12pt', max_length=10, verbose_name='Base Font Size')),
                ('heading_font_family', models.CharField(blank=True, help_text='Leave blank to use the same as body font', max_length=200, verbose_name='Heading Font Family')),
                ('header_background_color', models.CharField(default='#f5f5f5', max_length=7, verbose_name='Header Background Color')),
                ('header_text_color', models.CharField(default='#000000', max_length=7, verbose_name='Header Text Color')),
                ('header_height', models.CharField(default='80px', max_length=10, verbose_name='Header Height')),
                ('header_template', models.TextField(blank=True, help_text='Custom HTML for header. Leave blank for default.', verbose_name='Header HTML Template')),
                ('footer_background_color', models.CharField(default='#f5f5f5', max_length=7, verbose_name='Footer Background Color')),
                ('footer_text_color', models.CharField(default='#000000', max_length=7, verbose_name='Footer Text Color')),
                ('footer_height', models.CharField(default='60px', max_length=10, verbose_name='Footer Height')),
                ('footer_template', models.TextField(blank=True, help_text='Custom HTML for footer. Leave blank for default.', verbose_name='Footer HTML Template')),
                ('custom_css', models.TextField(blank=True, help_text='Additional CSS styles. Will be sanitized before use.', verbose_name='Custom CSS')),
                ('is_default', models.BooleanField(default=False, help_text='Only one theme can be default', verbose_name='Is Default')),
            ],
            options={
                'verbose_name': 'Report Theme',
                'verbose_name_plural': 'Report Themes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(help_text="Full report name (e.g., 'invoices.InvoiceReport')", max_length=200, unique=True, verbose_name='Report Name')),
                ('display_name', models.CharField(help_text='Human-readable name for the report', max_length=200, verbose_name='Display Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('text_direction', models.CharField(choices=[('ltr', 'Left-to-Right'), ('rtl', 'Right-to-Left')], default='ltr', help_text='Text direction for the report', max_length=3, verbose_name='Text Direction')),
                ('custom_css', models.TextField(blank=True, help_text='Report-specific CSS. Will be sanitized before use.', verbose_name='Custom CSS')),
                ('page_format', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='django_fancy_reports.reportpageformat', verbose_name='Page Format')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='django_fancy_reports.reporttheme', verbose_name='Theme')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['report_name'],
            },
        ),
    ]
