# Generated by Django 5.2.8 on 2026-01-28 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_fancy_reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporttheme',
            name='accent_color',
        ),
        migrations.RemoveField(
            model_name='reporttheme',
            name='custom_css',
        ),
        migrations.RemoveField(
            model_name='reporttheme',
            name='font_size',
        ),
        migrations.RemoveField(
            model_name='reporttheme',
            name='footer_background_color',
        ),
        migrations.RemoveField(
            model_name='reporttheme',
            name='footer_height',
        ),
        migrations.RemoveField(
            model_name='reporttheme',
            name='footer_template',
        ),
        migrations.RemoveField(
            model_name='reporttheme',
            name='footer_text_color',
        ),
        migrations.RemoveField(
            model_name='reporttheme',
            name='header_background_color',
        ),
        migrations.RemoveField(
            model_name='reporttheme',
            name='header_height',
        ),
        migrations.RemoveField(
            model_name='reporttheme',
            name='header_template',
        ),
        migrations.RemoveField(
            model_name='reporttheme',
            name='header_text_color',
        ),
        migrations.RemoveField(
            model_name='reporttheme',
            name='heading_font_family',
        ),
        migrations.RemoveField(
            model_name='reporttheme',
            name='text_color',
        ),
        migrations.AddField(
            model_name='reporttheme',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Optional background image for the report', null=True, upload_to='report_themes/backgrounds/', verbose_name='Background Image'),
        ),
        migrations.AddField(
            model_name='reporttheme',
            name='background_image_opacity',
            field=models.DecimalField(decimal_places=2, default=0.05, help_text='Opacity of background image (0.01 to 1.00). Lower is more subtle.', max_digits=3, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(1.0)], verbose_name='Background Image Opacity'),
        ),
        migrations.AddField(
            model_name='reporttheme',
            name='background_image_position',
            field=models.CharField(choices=[('center', 'Center'), ('top', 'Top'), ('bottom', 'Bottom'), ('left', 'Left'), ('right', 'Right'), ('top left', 'Top Left'), ('top right', 'Top Right'), ('bottom left', 'Bottom Left'), ('bottom right', 'Bottom Right')], default='center', help_text='Position of the background image', max_length=50, verbose_name='Background Image Position'),
        ),
        migrations.AddField(
            model_name='reporttheme',
            name='background_image_repeat',
            field=models.CharField(choices=[('no-repeat', 'No Repeat'), ('repeat', 'Repeat'), ('repeat-x', 'Repeat Horizontally'), ('repeat-y', 'Repeat Vertically')], default='no-repeat', help_text='Whether the background image should repeat', max_length=20, verbose_name='Background Image Repeat'),
        ),
        migrations.AddField(
            model_name='reporttheme',
            name='background_image_size',
            field=models.CharField(choices=[('cover', 'Cover (fill container)'), ('contain', 'Contain (fit inside)'), ('auto', 'Auto (original size)'), ('50%', '50% of container'), ('100%', '100% of container')], default='cover', help_text='How the background image should be sized', max_length=50, verbose_name='Background Image Size'),
        ),
        migrations.AddField(
            model_name='reporttheme',
            name='border_color',
            field=models.CharField(default='#dddddd', help_text='Table borders and dividers', max_length=7, verbose_name='Border Color'),
        ),
        migrations.AddField(
            model_name='reporttheme',
            name='header_bg_color',
            field=models.CharField(default='#f5f5f5', help_text='Background color for table headers', max_length=7, verbose_name='Table Header Background'),
        ),
        migrations.AlterField(
            model_name='reporttheme',
            name='font_family',
            field=models.CharField(default="'Helvetica Neue', Arial, sans-serif", help_text='Main font family for the report', max_length=200, verbose_name='Font Family'),
        ),
        migrations.AlterField(
            model_name='reporttheme',
            name='primary_color',
            field=models.CharField(default='#0F172A', help_text='Main text and headings color (e.g., #333333)', max_length=7, verbose_name='Primary Color'),
        ),
        migrations.AlterField(
            model_name='reporttheme',
            name='secondary_color',
            field=models.CharField(default='#666666', help_text='Secondary text color', max_length=7, verbose_name='Secondary Color'),
        ),
    ]
