# Generated by Django 5.2.8 on 2026-01-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_fancy_reports', '0002_remove_reporttheme_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttheme',
            name='row_even_bg_color',
            field=models.CharField(default='#ffffff', help_text='Background color for even rows (2nd, 4th, etc.)', max_length=7, verbose_name='Even Row Background'),
        ),
        migrations.AddField(
            model_name='reporttheme',
            name='row_odd_bg_color',
            field=models.CharField(default='#f9f9f9', help_text='Background color for odd rows (1st, 3rd, etc.)', max_length=7, verbose_name='Odd Row Background'),
        ),
    ]
